### ISSUE TITLE
Improvement on OpenWisp Firmware

### ISSUE THREAD

**Issue by claudyus** [vilpalu/OpenWISP-Firmware-clone#1]
Hi @vilpalu,
I'm happy that you are using Openwisp-firmware and I would like to invite you to contribute back with your improvement to the original repo.

I see some little fix that I would like to have in main repo. If you have any question on git workflow using fork/pull request I can suggest you those helpful tutorial:

https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow/

https://www.atlassian.com/git/tutorials/making-a-pull-request

**Comment by vilpalu** [comment]
hello, 
about what fix you are talking?

**Comment by claudyus** [comment]
If you proprietly fork the openwisp-firmware you can re-publish upstream improvement like:

https://github.com/vilpalu/OpenWISP-Firmware/commit/68a738baefc9488b08133f514f71633279bba274
https://github.com/vilpalu/OpenWISP-Firmware/commit/ffe09067f68e08c2ec617880452676bb79757f08
https://github.com/vilpalu/OpenWISP-Firmware/commit/d3d49cd8eb456688dc947b13da9c83c9f43a916c
